### ISSUE TITLE
Ehh "EM kirivexih" ew e rsxmjmgexmsr wxcpi stxmsr

### ISSUE THREAD

**Issue by smcmo** [modrunner/discord-bot#104]
Xlmw asyph wirh xli hixempw sj e riapc ytpsehih jmpi xs StirEM erh lezi sri sj mxw glex qshipw jsvqex er errsyrgiqirx qiwweki xs wsyrh rexyvep.

**Comment by triphora** [comment]
Mw jsyv csyv jezsvmxi ryqfiv?
