### ISSUE TITLE
[Enhancement] Add Support for all the Categories on Modrinth

### ISSUE THREAD

**Issue by Cyclopropinon** [modrunner/discord-bot#106]
### Suggestion Type

Suggesting an update to existing functionality

### Description

These Categories would be: 
![grafik](https://github.com/modrunner/discord-bot/assets/119750500/f5ebffbb-4ccb-4e96-aa70-741ebb15522b)

**Comment by smcmo** [comment]
Modrunner already supports both tracking & searching for projects in all categories. If that's not what you intend can you be more specific?

**Comment by Cyclopropinon** [comment]
I missed it lmao. sorry for that.
